# Generated by Django 2.2.16 on 2020-09-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('correo', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=3)),
                ('telofono', models.CharField(max_length=10)),
                ('genero', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=10)),
                ('nacionalidad', models.CharField(max_length=30)),
            ],
        ),
    ]
