# Generated by Django 3.1.2 on 2020-11-26 23:02

import Maipo.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_clienteExterno', models.BooleanField(default=False)),
                ('is_clienteInterno', models.BooleanField(default=False)),
                ('is_productor', models.BooleanField(default=False)),
                ('is_transportista', models.BooleanField(default=False)),
                ('is_consultor', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Maipo\\media')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='clienteExterno',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Maipo.user')),
                ('nombre', models.CharField(max_length=60)),
                ('ID', models.CharField(max_length=10)),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('region', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=60)),
                ('codigopostal', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='clienteLocal',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Maipo.user')),
                ('nombre', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=40)),
                ('comuna', models.CharField(default='Maipu', max_length=60)),
                ('codigopostal', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Maipo.user')),
                ('nombre', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=3)),
                ('telefono', models.CharField(max_length=10)),
                ('genero', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=500)),
                ('nacionalidad', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Maipo.user')),
                ('nombre', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=10)),
                ('telefono', models.IntegerField()),
                ('peso_max_camion', models.IntegerField(default=12)),
                ('peso_min_camion', models.IntegerField(default=12)),
                ('matricula', models.CharField(default='AAAAAA', max_length=6)),
                ('tipoDeVenta', models.CharField(choices=[('Venta Interna', 'Venta Interna'), ('Venta Externa', 'Venta Externa')], default='Venta Interna', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='subasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('precioInicial', models.IntegerField()),
                ('ultimaApuesta', models.IntegerField(null=True)),
                ('pesoProductos', models.IntegerField()),
                ('vistas', models.IntegerField()),
                ('direccionEntrega', models.CharField(default='Contactar Client', max_length=50)),
                ('tipoDeVenta', models.CharField(choices=[('Venta Interna', 'Venta Interna'), ('Venta Externa', 'Venta Externa')], default='Venta Interna', max_length=13)),
                ('fechaInicio', models.DateField(auto_now=True)),
                ('fechaTermino', models.DateField()),
                ('productos', models.ManyToManyField(to='Maipo.Producto')),
                ('ultimoEditor', models.ForeignKey(blank=True, null=True, on_delete=models.SET(Maipo.models.User), to=settings.AUTH_USER_MODEL)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maipo.productor')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='Productor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Maipo.productor'),
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagoRealizado', models.BooleanField(default=False)),
                ('valor_Total', models.FloatField()),
                ('estadoDelPedido', models.CharField(choices=[('Pagado', 'Pagado'), ('En_Subasta', 'En Subasta'), ('En_Camino', 'En Camino'), ('Finalizado', 'Finalizado')], default='Pagado', max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('productos', models.ManyToManyField(to='Maipo.Producto')),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Maipo.productor')),
                ('transportista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Maipo.transportista')),
            ],
        ),
    ]
