# Generated by Django 3.1.2 on 2020-11-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clienteExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=60)),
                ('codigopostal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='clienteLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('correo', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=3)),
                ('telefono', models.CharField(max_length=10)),
                ('genero', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=10)),
                ('nacionalidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=10)),
                ('tipoLicencia', models.CharField(max_length=1)),
            ],
        ),
    ]
