# Generated by Django 3.1.2 on 2020-11-26 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maipo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientelocal',
            old_name='region',
            new_name='regiones',
        ),
    ]
