# Generated by Django 3.1.2 on 2020-11-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maipo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='productor',
            name='direccion',
            field=models.CharField(max_length=500),
        ),
    ]
