# Generated by Django 2.2.16 on 2020-10-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clienteExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=60)),
                ('codigopostal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='clienteLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=10)),
                ('tipoLicencia', models.CharField(max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='productor',
            old_name='telofono',
            new_name='telefono',
        ),
    ]
