# Generated by Django 3.1.2 on 2020-11-12 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maipo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportista',
            name='tipoLicencia',
        ),
        migrations.AddField(
            model_name='producto',
            name='Productor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maipo.productor'),
        ),
        migrations.AddField(
            model_name='transportista',
            name='matricula',
            field=models.CharField(default='AAAAAA', max_length=6),
        ),
        migrations.AddField(
            model_name='transportista',
            name='peso_max_camion',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='transportista',
            name='peso_min_camion',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='transportista',
            name='tipoDeVenta',
            field=models.CharField(choices=[('Venta Interna', 'Venta Interna'), ('Venta Externa', 'Venta Externa')], default='Venta Interna', max_length=13),
        ),
        migrations.CreateModel(
            name='subasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('precioInicial', models.IntegerField()),
                ('vistas', models.IntegerField()),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maipo.productor')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maipo.producto')),
            ],
        ),
    ]
