# Generated by Django 2.2.16 on 2020-10-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maipo', '0002_auto_20201003_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_Externo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Interno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
