# Generated by Django 3.1.2 on 2020-11-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maipo', '0002_auto_20201111_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='pesoProductos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
