# Generated by Django 3.1.2 on 2020-11-13 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maipo', '0003_subasta_pesoproductos'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='ultimoEditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maipo.transportista'),
        ),
    ]
