# Generated by Django 3.1.2 on 2020-11-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maipo', '0004_subasta_ultimoeditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='DireccionEntrega',
            field=models.CharField(default='Contactar Productor', max_length=50),
        ),
    ]
