# Generated by Django 3.1.2 on 2020-11-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maipo', '0005_subasta_direccionentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='ultimaApuesta',
            field=models.IntegerField(null=True),
        ),
    ]
