# Generated by Django 3.1.2 on 2020-11-13 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maipo', '0007_role_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
