# Generated by Django 3.1.2 on 2020-11-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maipo', '0008_auto_20201113_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Productor',
        ),
        migrations.AddField(
            model_name='producto',
            name='Productor',
            field=models.ManyToManyField(blank=True, null=True, to='Maipo.Productor'),
        ),
    ]
