# Generated by Django 3.1.2 on 2020-11-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maipo', '0009_auto_20201114_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='productos',
        ),
        migrations.AddField(
            model_name='subasta',
            name='productos',
            field=models.ManyToManyField(to='Maipo.Producto'),
        ),
    ]
